version: "3"
services:
  # API
  api:
    container_name: fastapi
    build: ./api
    command: uvicorn carbon.main:app --host 0.0.0.0
    volumes:
      - ./api:/app
    ports:
      - 8081:8000
    environment:
      DATABASE_URL: postgresql://clinique:clinique@db/clinique_db
    depends_on:
      - db

  # Database
  db:
    container_name: postgres
    image: postgres:13-alpine
    restart: always
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: clinique
      POSTGRES_PASSWORD: clinique
      POSTGRES_DB: clinique_db

  # PGAdmin
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8082:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  # Front-End
  website:
    container_name: nginx
    image: nginx:stable
    ports: 
      - "8080:80"
    restart: always


# Persistent Storage
volumes:
  postgres_data:
  pgadmin-data:

