version: "3"
services:
  # API
  api:
    container_name: fastapi
    build: ./api
    command: uvicorn carbon.main:app --host 0.0.0.0 --reload
    volumes:
      - ./api:/app
    ports:
      - 8081:8000
    environment:
      DATABASE_URL: postgresql://clinique:clinique@db/clinique_db
    depends_on:
      - db
    restart: on-failure

  # Database
  db:
    container_name: postgres
    image: postgres:13-alpine
    restart: always
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: clinique
      POSTGRES_PASSWORD: clinique
      POSTGRES_DB: clinique_db

  # PGAdmin
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8082:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  # Front-End
  website:
    container_name: nginx
    image: nginx:stable
    ports: 
      - "8080:80"
    restart: always

  # Gitlab
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ee:latest
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - "8089:80"
      - "8443:443"
      - "22:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

# Persistent Storage
volumes:
  postgres_data:
  pgadmin-data:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
