"""update user & group table

Revision ID: 18ce6d96c0ab
Revises: cdb730ab18c4
Create Date: 2022-11-23 22:08:32.266367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ce6d96c0ab'
down_revision = 'cdb730ab18c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'group', ['group_name'])
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_constraint(None, 'group', type_='unique')
    # ### end Alembic commands ###
