"""revise group table

Revision ID: 503ee6aa81d1
Revises: 18ce6d96c0ab
Create Date: 2022-11-27 13:39:06.394093

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = '503ee6aa81d1'
down_revision = '18ce6d96c0ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('uid', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True))
    op.create_unique_constraint('uid', 'group', ['uid'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'uid')
    # ### end Alembic commands ###
