"""add user_group table

Revision ID: 70d2ced2b2fb
Revises: ceb1daa5e183
Create Date: 2022-11-14 23:12:44.021344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d2ced2b2fb'
down_revision = 'ceb1daa5e183'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group'], ['group.id'], name='fk_users_groups_group_group_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name='fk_users_groups_user_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('fk_user_group_id_group_id', 'user', type_='foreignkey')
    op.drop_column('user', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_user_group_id_group_id', 'user', 'group', ['group_id'], ['id'])
    op.drop_table('users_groups')
    # ### end Alembic commands ###
