"""update group table

Revision ID: cdb730ab18c4
Revises: 70d2ced2b2fb
Create Date: 2022-11-15 22:52:05.565861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb730ab18c4'
down_revision = '70d2ced2b2fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('group_name', sa.String(length=128), nullable=False))
    op.drop_column('group', 'member_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('group', 'group_name')
    # ### end Alembic commands ###
